name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Dashboard code
      uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: latest
    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: '17.x'
        cache: npm
    - name: Install package and build
      run: |
        npm install
        npm build
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: dist
